services:
  - type: web
    name: image-generator-bot
    runtime: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REPLICATE_API_KEY
        sync: false
      - key: RENDER_URL
        value: "https://image-generator-bot.onrender.com"  # замени на свой Render URL
      - key: WEBHOOK_PATH
        value: "webhook"  # можно поменять на секретный путь
